name: build

on:
  push:
    branches: [ master ]

jobs:
  build-ubuntu:
    name: Ubuntu - GCC
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Installing Dependencies
      run: sudo apt-get update && sudo apt-get install libgtk-3-dev
    - name: Configure
      run: mkdir build && mkdir install && cd build && cmake -DCMAKE_INSTALL_PREFIX="../install" -DCMAKE_BUILD_TYPE=Release ..
    - name: Build
      run: cmake --build build --target install
    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu
        path: |
          install/lib/*
  
  build-macos:
    name: MacOS latest - Clang
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure
      run: mkdir build && mkdir install && cd build && cmake -DCMAKE_INSTALL_PREFIX="../install" -DCMAKE_BUILD_TYPE=Release ..
    - name: Build
      run: cmake --build build --target install
    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: mac
        path: |
          install/lib/*
  
  build-windows:
    name: Windows latest - MSVC
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure
      run: mkdir build && mkdir install && cd build && cmake -DCMAKE_INSTALL_PREFIX="../install" ..
    - name: Build
      run: cmake --build build --target install --config Release
    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: mac
        path: |
          install/lib/*
